server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:expensetracker
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  redis:
    host: redis
    port: 6379

jwt:
  secret: mysecretkey
  expiration: 86400000

swagger:
  enabled: true 